apiVersion: apps/v1
kind: Deployment
metadata:
  name: security-demo
  namespace: security-demo
  labels:
    app: security-demo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: security-demo
  template:
    metadata:
      labels:
        app: security-demo
    spec:
      containers:
        - name: security-demo
          image: __APP_IMAGE__
          ports:
            - containerPort: 8080
          readinessProbe:
            httpGet:
              path: /greet?name=healthcheck
              port: 8080
            initialDelaySeconds: 5
            periodSeconds: 3
---
apiVersion: v1
kind: Service
metadata:
  name: security-demo
  namespace: security-demo
spec:
  selector:
    app: security-demo
  ports:
    - port: 8080
      targetPort: 8080
